baseURL = "https://ry0.org/"
languageCode = "en-us"
title = "Ry O"
theme = "PaperMod"
enableRobotsTXT = true

# Menu
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 3

# Social links
#[params.social]
#  github = "https://github.com/ry0kc"
#  email = "raozmc@gmail.com"

# Optional display options
[params]
  showReadingTime = true
  showShareButtons = true
  defaultTheme = "system"
  ShowFooter = true
